services:
  mongo-db-test:
    image: mongo:6.0.6
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_BD_NAME} 
    volumes:
      - ./mongo-test:/data/db
    ports:
      - 27017:27017