version: '3.8'

services:
  websocket-server:
    build: .
    container_name: websocket-server
    ports:
      - "3000:3000" # puerto expuesto para usar desde Postman o navegador
    env_file:
      - .env
    restart: unless-stopped
